os:
  - linux
language: python
python:
  - "3.8"  # 3.8 development branch
# command to install dependencies
install:
  - pip install --user https://github.com/matplotlib/basemap/archive/master.zip
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest