os:
  - linux
language: python
python:
  - "3.8"  # 3.8 development branch
# command to install dependencies
install:
  - pip3 install --upgrade pip
  - pip install libgeos-3.5.0
  - pip install libgeos-dev
  - pip install https://github.com/matplotlib/basemap/archive/master.zip
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest