os:
  - linux
language: python
python:
  - "3.8"  # 3.8 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install "basemap == 1.3.2" "basemap-data == 1.3.2"
  - pip install .
# command to run tests
script:
  - pytest